fastlane_version "2.94.0"
default_platform :ios
platform :ios do
   lane :example do
      puts("this is my first 🚀 lane")
   end
   error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
end
